[custom]
;This is an example external configuration file
;All possible customization settings are shown below
;Thanks sukka & acl4SSR & blackmatrix7

;Options for custom groups
custom_proxy_group=Direct`select`[]DIRECT
custom_proxy_group=RejectDrop`select`[]REJECT-DROP`[]REJECT`[]DIRECT
custom_proxy_group=Reject`select`[]REJECT`[]REJECT-DROP`[]DIRECT
custom_proxy_group=CDN`select`[]美国低倍率`[]香港低倍率`[]DIRECT`[]手动切换
custom_proxy_group=Download`select`[]美国低倍率`[]香港低倍率`[]DIRECT`[]手动切换
custom_proxy_group=AI`select`[]美国节点`[]香港节点`[]手动切换
custom_proxy_group=Telegram`select`[]美国节点`[]香港节点`[]手动切换
custom_proxy_group=AppleServices`select`[]DIRECT`[]美国节点`[]香港节点`[]手动切换
custom_proxy_group=Apple`select`[]DIRECT`[]美国节点`[]香港节点`[]手动切换
custom_proxy_group=Microsoft`select`[]香港节点`[]DIRECT`[]美国节点`[]手动切换
custom_proxy_group=Google`select`[]美国节点`[]香港节点`[]手动切换
custom_proxy_group=Stream`select`[]美国低倍率`[]DIRECT`[]香港低倍率`[]狮城节点`[]日本节点`[]台湾省节点`[]韩国节点`[]其他地区`手动切换
custom_proxy_group=Proxy`select`[]美国节点`[]香港节点`[]狮城节点`[]日本节点`[]台湾省节点`[]韩国节点`[]其他地区`[]手动切换`[]DIRECT
custom_proxy_group=match`select`[]香港节点`[]美国节点`[]狮城节点`[]日本节点`[]台湾省节点`[]韩国节点`[]其他地区`手动切换`[]DIRECT
custom_proxy_group=relay`url-test`(US|United States)`http://www.gstatic.com/generate_204`300,5,50
custom_proxy_group=美国节点`select`(US|United States|美国)
custom_proxy_group=美国低倍率`select`(US|United States|美国)
custom_proxy_group=香港节点`select`(HK|Hong Kong|香港)
custom_proxy_group=香港低倍率`select`(HK|Hong Kong|香港)
custom_proxy_group=狮城节点`select`(SG|Singapore|新加坡)
custom_proxy_group=日本节点`select`(JP|Japan|日本)
custom_proxy_group=台湾省节点`select`(TW|Taiwan|台湾)
custom_proxy_group=韩国节点`select`(KR|Korea|韩国)
custom_proxy_group=其他地区`select`(^(?!.*(Expire|Traffic|HK|Honk Kong|香港|TW|Taiwan|台湾|SG|Singapore|新加坡|KR|Korea|韩国|US|United States|美国|JP|Japan|日本|测试)).*)
custom_proxy_group=手动切换`select`(^(?!.*(Expire|Traffic|测试)).*)

;Options for custom rulesets
enable_rule_generator=true
overwrite_original_rules=true
ruleset=Direct,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/non_ip/lan.yaml,86400
ruleset=Direct,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/non_ip/direct.yaml,86400
ruleset=RejectDrop,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/non_ip/reject-drop.yaml,86400
ruleset=Reject,clash-domain:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/domainset/reject.yaml,86400
ruleset=Reject,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/non_ip/reject.yaml,86400
ruleset=Reject,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/non_ip/reject-no-drop.yaml,86400
ruleset=Direct,clash-domain:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/domainset/apple_cdn.yaml,86400
ruleset=Direct,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/non_ip/microsoft_cdn.yaml,86400
ruleset=Direct,clash-domain:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/domainset/game-download.yaml,86400
ruleset=CDN,clash-domain:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/domainset/cdn.yaml,86400
ruleset=CDN,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/non_ip/cdn.yaml,86400
ruleset=Download,clash-domain:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/domainset/download.yaml,86400
ruleset=Download,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/non_ip/download.yaml,86400
ruleset=AI,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/non_ip/ai.yaml,86400
ruleset=Telegram,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/non_ip/telegram.yaml,86400
ruleset=Direct,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/non_ip/apple_cn.yaml,86400
ruleset=AppleServices,clash-domain:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/domainset/icloud_private_relay.yaml,86400
ruleset=AppleServices,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/non_ip/apple_intelligence.yaml,86400
ruleset=Apple,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/non_ip/apple_services.yaml,86400
ruleset=Microsoft,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/non_ip/microsoft.yaml,86400
ruleset=Stream,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/non_ip/stream.yaml,86400
ruleset=Google,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/non_ip/google.yaml,86400
ruleset=Proxy,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/non_ip/global.yaml,86400
ruleset=Direct,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/non_ip/domestic.yaml,86400
ruleset=Direct,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/ip/lan.yaml,86400
ruleset=Reject,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/ip/reject.yaml,86400
ruleset=CDN,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/ip/cdn.yaml,86400
ruleset=Download,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/ip/download.yaml,86400
ruleset=Telegram,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/ip/telegram.yaml,86400
ruleset=Apple,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/ip/apple_services.yaml,86400
ruleset=Stream,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/ip/stream.yaml,86400
ruleset=Direct,clash-classic:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/ip/domestic.yaml,86400
ruleset=Direct,clash-ipcidr:https://raw.githubusercontent.com/taplus/CustomRules/refs/heads/main/rulesets/sukka/ip/china_ip.yaml,86400
ruleset=match,[]MATCH

;Options for custom base configuration file
clash_rule_base=https://raw.githubusercontent.com/taplus/CustomRules/main/templates/clash.yml
;quanx_rule_base=https://raw.githubusercontent.com/taplus/CustomRules/main/templates/quanx.conf